name: zoo
description: "Zoo de Lisboa"


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.9
  provider: ^6.1.1
  youtube_player_flutter: ^8.1.2
  cupertino_icons: ^1.0.2
  photo_view: ^0.14.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/mapa.png
    - lib/assets/news1.png
    - lib/assets/news2.png
    - lib/assets/news3.png
    - lib/assets/historia1.png
    - lib/assets/historia2.png
    - lib/assets/atracao1.png
    - lib/assets/atracao2.png
    - lib/assets/atracao3.png
    - lib/assets/atracao4.png
    - lib/assets/atracao5.png
    - lib/assets/atracao6.png
    - lib/assets/atracao7.png
    - lib/assets/atracao8.png
    - lib/assets/atracao9.png
    - lib/assets/atracao10.png